continuous_event_time_col: READMISSION_30_DAYS
event_id_col: HADM_ID
event_name: readmission
event_time_cat_col: READMISSION_TIME_CAT
event_time_feature_col: READMISSION_30_DAYS
feature_define_state_labels: READMISSION_30_DAYS
features:
  DISCHARGE_LOCATION_POST_ACUTE_CARE: bernoulli
  LOG_DAYS_IN_ICU: gaussian
  LOG_NUM_DRUGS: gaussian
  NUM_COMORBIDITIES: poisson
  READMISSION_30_DAYS: bernoulli
hidden_state_labels:
- low
- medium_1
- medium_2
- high
id_col: SUBJECT_ID
model_name: hmm_mimic_time_binary_30_days
n_states: 4
save_model_path: /workspaces/master-thesis-recurrent-health-events-prediction/_models/mimic/hmm
time_col: ADMITTIME
use_only_sequences_gte_2_steps: false
