add_distribution_params:
  READMISSION_TIME_CAT_ENCODED:
    labels:
    - 0-30
    - 30-120
    - 120+
    n_categories: 3
continuous_event_time_col: LOG_DAYS_UNTIL_NEXT_HOSPITALIZATION
event_id_col: HADM_ID
event_name: readmission
event_time_cat_col: READMISSION_TIME_CAT
event_time_feature_col: READMISSION_TIME_CAT_ENCODED
feature_define_state_labels: READMISSION_TIME_CAT_ENCODED
features:
  DISCHARGE_LOCATION_POST_ACUTE_CARE: bernoulli
  LOG_DAYS_IN_ICU: gaussian
  NUM_COMORBIDITIES: poisson
  READMISSION_TIME_CAT_ENCODED: categorical
hidden_state_labels:
- high_2
- high_1
- medium
- low_2
- low_1
id_col: SUBJECT_ID
model_name: hmm_mimic_categorical_time
n_states: 5
save_model_path: /workspaces/master-thesis-recurrent-health-events-prediction/_models/mimic/hmm
time_col: ADMITTIME
use_only_sequences_gte_2_steps: false
